# Generated by Django 6.0.3 on 2026-04-09 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='review',
        ),
    ]
